{% set version = "0.6.1" %}

package:
  name: whichcraft
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/whichcraft/whichcraft-{{ version }}.tar.gz
  sha256: acdbb91b63d6a15efbd6430d1d7b2d36e44a71697e93e19b7ded477afd9fce87

build:
  noarch: python
  number: 1
  script: 
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  source_files:
    - test_whichcraft.py
  requires:
    - coverage
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - whichcraft
  commands:
    - pip check
    - coverage run --source=whichcraft --branch pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under 100

about:
  home: https://github.com/pydanny/whichcraft
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >
            This package provides cross-platform cross-python shutil.which
            functionality.

extra:
  recipe-maintainers:
    - bollwyvl
    - pydanny
